// Copyright (c) 2002-present, OpenMS Inc. -- EKU Tuebingen, ETH Zurich, and FU Berlin
// SPDX-License-Identifier: BSD-3-Clause
//
// --------------------------------------------------------------------------
// $Maintainer: Tom Mueller $
// $Authors: Tom Mueller $
// --------------------------------------------------------------------------

#include <OpenMS/CONCEPT/ClassTest.h>
#include <OpenMS/ANALYSIS/TOPDOWN/FLASHIda/Config.h>

#include <nlohmann/json.hpp>

#include <fstream>
#include <sstream>
#include <string>

using namespace OpenMS;
using json = nlohmann::json;

// ---------------------------------------------------------------------------
// Schema drift guard (C++ side). The shared reference fixture
// FlashIDA/test-data/config_schema_reference.json is GENERATED by the C# side
// (MethodParameters.GenerateReferenceConfigJson). This test proves:
//   - EveryKey_ParsesToOnDiskValue: the C++ Config reader binds every key to the value ON DISK
//     (parsed value == raw JSON value per field — no hard-coded sentinels, so it tracks the
//     generator automatically). If C++ silently defaults a key whose on-disk value differs, it fails.
//   - UnknownKey_Throws: the C++ Config reader hard-rejects any key with no schema home.
// The C# side (Flash.Tests/ConfigSchemaParityTests) proves the emitter + strict loader. Together the
// two schemas cannot silently diverge.
// ---------------------------------------------------------------------------

START_TEST(ConfigSchemaParity, "$Id$")

std::string json_str;
{
  std::ifstream in("../../FlashIDA/test-data/config_schema_reference.json");
  std::stringstream ss;
  ss << in.rdbuf();
  json_str = ss.str();
}

START_SECTION(reference_fixture_is_readable)
{
  TEST_EQUAL(json_str.empty(), false)
  TEST_EQUAL(json_str[0], '{')
}
END_SECTION

START_SECTION(EveryKey_ParsesToOnDiskValue)
{
  json j = json::parse(json_str);
  Config cfg(json_str);

  // --- deconvolution ---
  TEST_EQUAL(cfg.deconvolution().min_charge, j["deconvolution"]["min_charge"].get<int>())
  TEST_EQUAL(cfg.deconvolution().max_charge, j["deconvolution"]["max_charge"].get<int>())
  TEST_REAL_SIMILAR(cfg.deconvolution().min_mass, j["deconvolution"]["min_mass"].get<double>())
  TEST_REAL_SIMILAR(cfg.deconvolution().max_mass, j["deconvolution"]["max_mass"].get<double>())
  TEST_REAL_SIMILAR(cfg.targeting().qscore_threshold, j["deconvolution"]["score_threshold"].get<double>())
  TEST_REAL_SIMILAR(cfg.targeting().tqscore_threshold, j["deconvolution"]["tqscore_threshold"].get<double>())
  TEST_REAL_SIMILAR(cfg.targeting().tag_matching_tolerance_ppm, j["deconvolution"]["tol"][1].get<double>())

  // --- precursor_selection ---
  TEST_REAL_SIMILAR(cfg.targeting().rt_window, j["precursor_selection"]["RT_window"].get<double>())
  TEST_EQUAL(cfg.targeting().mode, j["precursor_selection"]["target_mode"].get<int>())
  TEST_EQUAL(cfg.targeting().consider_all_charges, j["precursor_selection"]["AllCharges"].get<bool>())
  TEST_EQUAL(cfg.targeting().charge_based_exclusion, j["precursor_selection"]["ChargeBasedExclusion"].get<bool>())
  TEST_EQUAL(cfg.targeting().hcd_energy, j["precursor_selection"]["HCDEnergy"].get<int>())
  TEST_EQUAL(cfg.targeting().strict_inclusion, j["precursor_selection"]["strict_inclusion"].get<bool>())
  TEST_REAL_SIMILAR(cfg.targeting().tie_threshold, j["precursor_selection"]["tie_threshold"].get<double>())

  // --- flashtnt ---
  TEST_EQUAL(cfg.targeting().min_tag_length, j["flashtnt"]["min_length"].get<int>())
  TEST_EQUAL(cfg.targeting().max_tag_length, j["flashtnt"]["max_length"].get<int>())
  TEST_EQUAL(cfg.targeting().max_total_ptm_count, j["flashtnt"]["max_ptm_count"].get<int>())
  TEST_REAL_SIMILAR(cfg.targeting().max_flanking_mass_diff, j["flashtnt"]["max_flanking_mass_diff"].get<double>())
  TEST_EQUAL(cfg.targeting().allow_gap, j["flashtnt"]["allow_gap"].get<bool>())
  TEST_EQUAL(cfg.targeting().max_aa_in_gap, j["flashtnt"]["max_aa_in_gap"].get<int>())
  TEST_EQUAL(cfg.targeting().max_blind_mod_count, j["flashtnt"]["max_blind_mod_count"].get<int>())
  TEST_REAL_SIMILAR(cfg.targeting().max_mod_mass, j["flashtnt"]["max_mod_mass"].get<double>())
  TEST_EQUAL(cfg.targeting().fixed_mod.size(), j["flashtnt"]["fixed_mod"].size())
  TEST_EQUAL(cfg.targeting().fixed_mod.empty() ? std::string("") : cfg.targeting().fixed_mod[0],
             j["flashtnt"]["fixed_mod"][0].get<std::string>())

  // --- tagging.follow_up_scan ---
  TEST_EQUAL(cfg.targeting().tagging_follow_up_scan.analyzer, j["tagging"]["follow_up_scan"]["analyzer"].get<std::string>())
  TEST_EQUAL(cfg.targeting().tagging_follow_up_scan.activation, j["tagging"]["follow_up_scan"]["activation"].get<std::string>())
  TEST_EQUAL(cfg.targeting().tagging_follow_up_scan.collision_energy, j["tagging"]["follow_up_scan"]["collision_energy"].get<int>())
  TEST_EQUAL(cfg.targeting().tagging_follow_up_scan.resolution, j["tagging"]["follow_up_scan"]["resolution"].get<int>())

  // --- conditional_ms2 ---
  TEST_EQUAL(cfg.targeting().conditional_ms2_enabled, j["conditional_ms2"].get<bool>())

  // --- quantification ---
  TEST_EQUAL(cfg.quantification().enabled, j["quantification"]["enabled"].get<bool>())
  TEST_REAL_SIMILAR(cfg.quantification().reporter_mz_tol, j["quantification"]["reporter_mz_tol"].get<double>())
  TEST_REAL_SIMILAR(cfg.quantification().fold_change_threshold, j["quantification"]["fold_change_threshold"].get<double>())

  // --- faims ---
  TEST_EQUAL(cfg.faims().cv_values.size(), j["faims"]["cv_values"].size())
  TEST_REAL_SIMILAR(cfg.faims().cv_values[0], j["faims"]["cv_values"][0].get<double>())
  TEST_EQUAL(cfg.faims().max_cv_skip, j["faims"]["max_cv_skip"].get<int>())
  TEST_EQUAL(cfg.faims().precursor_threshold, j["faims"]["cv_precursor_threshold"].get<int>())

  // --- ms_settings.ms1 -> level(1).scans[0] ---
  const auto& ms1 = cfg.level(1).scans[0];
  const auto& jms1 = j["ms_settings"]["ms1"];
  TEST_EQUAL(ms1.analyzer, jms1["analyzer"].get<std::string>())
  TEST_REAL_SIMILAR(ms1.first_mass, jms1["first_mass"].get<double>())
  TEST_REAL_SIMILAR(ms1.last_mass, jms1["last_mass"].get<double>())
  TEST_EQUAL(ms1.resolution, jms1["resolution"].get<int>())
  TEST_EQUAL(ms1.agc_target, jms1["agc_target"].get<int>())
  TEST_REAL_SIMILAR(ms1.max_it, jms1["max_it"].get<double>())
  TEST_EQUAL(ms1.microscans, jms1["microscans"].get<int>())
  TEST_REAL_SIMILAR(ms1.rf_lens, jms1["rf_lens"].get<double>())
  TEST_REAL_SIMILAR(ms1.source_cid, jms1["source_cid"].get<double>())
  TEST_REAL_SIMILAR(ms1.source_cid_scaling, jms1["source_cid_scaling"].get<double>())
  TEST_EQUAL(ms1.data_type, jms1["data_type"].get<std::string>())

  // --- ms_settings.ms2 / ms3 ---
  const auto& ms2 = cfg.level(2).scans[0];
  const auto& jms2 = j["ms_settings"]["ms2"][0];
  TEST_EQUAL(ms2.analyzer, jms2["analyzer"].get<std::string>())
  TEST_EQUAL(ms2.activation, jms2["activation"].get<std::string>())
  TEST_EQUAL(ms2.collision_energy, jms2["collision_energy"].get<int>())
  TEST_EQUAL(ms2.resolution, jms2["resolution"].get<int>())
  TEST_EQUAL(ms2.agc_target, jms2["agc_target"].get<int>())
  TEST_REAL_SIMILAR(ms2.max_it, jms2["max_it"].get<double>())
  TEST_REAL_SIMILAR(ms2.first_mass, jms2["first_mass"].get<double>())
  TEST_REAL_SIMILAR(ms2.last_mass, jms2["last_mass"].get<double>())
  TEST_EQUAL(ms2.microscans, jms2["microscans"].get<int>())
  TEST_REAL_SIMILAR(ms2.reaction_time, jms2["reaction_time"].get<double>())
  const auto& ms3 = cfg.level(3).scans[0];
  const auto& jms3 = j["ms_settings"]["ms3"][0];
  TEST_EQUAL(ms3.activation, jms3["activation"].get<std::string>())
  TEST_EQUAL(ms3.collision_energy, jms3["collision_energy"].get<int>())
  TEST_EQUAL(ms3.resolution, jms3["resolution"].get<int>())

  // --- scheduling ---
  TEST_EQUAL(cfg.scheduling().cycle_time_enabled, j["scheduling"]["cycle_time"]["enabled"].get<bool>())
  TEST_REAL_SIMILAR(cfg.scheduling().cycle_time_ms, j["scheduling"]["cycle_time"]["value_ms"].get<double>())
  TEST_EQUAL(cfg.scheduling().timeout_enabled, j["scheduling"]["scan_timeout"]["enabled"].get<bool>())
  TEST_REAL_SIMILAR(cfg.scheduling().timeout_ms, j["scheduling"]["scan_timeout"]["value_ms"].get<double>())
  TEST_EQUAL((int)cfg.scheduling().agc_interval_ms,
             (int)(j["scheduling"]["agc_interval_seconds"].get<double>() * 1000.0))

  // --- characterization ---
  std::string obj = j["characterization"]["objective"].get<std::string>();
  TEST_EQUAL((int)cfg.characterization().objective,
             (int)(obj == "coverage" ? CharacterizationObjective::Coverage : CharacterizationObjective::Ambiguity))
  TEST_EQUAL(cfg.characterization().protein_sequence, j["characterization"]["protein_sequence"].get<std::string>())
  TEST_EQUAL(cfg.characterization().ms3_all_charges, j["characterization"]["ms3_all_charges"].get<bool>())

  // --- selection_strategy ---
  TEST_EQUAL(cfg.level(1).max_targets, j["selection_strategy"]["ms1"]["max_targets"].get<int>())
  TEST_EQUAL(cfg.level(1).min_charge, j["selection_strategy"]["ms1"]["min_charge"].get<int>())
  TEST_EQUAL(cfg.level(2).max_targets, j["selection_strategy"]["ms2"]["max_targets"].get<int>())
  TEST_EQUAL(cfg.level(2).min_charge, j["selection_strategy"]["ms2"]["min_charge"].get<int>())
  TEST_EQUAL((int)cfg.level(2).exploration, (int)ExplorationMetric::MassCount)
  const auto& jex2 = j["selection_strategy"]["ms2"]["exploration"];
  TEST_REAL_SIMILAR(cfg.level(2).ce_min, jex2["ce_min"].get<double>())
  TEST_REAL_SIMILAR(cfg.level(2).ce_max, jex2["ce_max"].get<double>())
  TEST_REAL_SIMILAR(cfg.level(2).ce_step, jex2["ce_step"].get<double>())
  TEST_REAL_SIMILAR(cfg.level(2).remaining_precursor_target, jex2["remaining_precursor_target"].get<double>())
  TEST_EQUAL((int)cfg.level(3).selection, (int)SelectionMetric::None)
}
END_SECTION

START_SECTION(UnknownKey_Throws)
{
  // A key with no schema home must throw std::invalid_argument at parse time — at every level.
  TEST_EXCEPTION(std::invalid_argument, Config(std::string(R"({ "bogus_top": 1 })")))
  TEST_EXCEPTION(std::invalid_argument, Config(std::string(R"({ "precursor_selection": { "bogus": 1 } })")))
  TEST_EXCEPTION(std::invalid_argument, Config(std::string(R"({ "ms_settings": { "ms1": { "IsolationMode": "Quadrupole" } } })")))
  TEST_EXCEPTION(std::invalid_argument, Config(std::string(R"({ "flashtnt": { "typo": 1 } })")))
  TEST_EXCEPTION(std::invalid_argument, Config(std::string(R"({ "ms3": { "enabled": true } })")))   // legacy top-level section
}
END_SECTION

END_TEST
