// Copyright (c) 2002-present, OpenMS Inc. -- EKU Tuebingen, ETH Zurich, and FU Berlin
// SPDX-License-Identifier: BSD-3-Clause
//
// --------------------------------------------------------------------------
// $Maintainer: Tom Mueller $
// $Authors: Tom Mueller $
// --------------------------------------------------------------------------

#include <OpenMS/CONCEPT/ClassTest.h>
#include <OpenMS/ANALYSIS/TOPDOWN/FLASHIda/Config.h>

#include <nlohmann/json.hpp>

#include <fstream>
#include <sstream>
#include <string>

using namespace OpenMS;
using json = nlohmann::json;

// ---------------------------------------------------------------------------
// Schema drift guard (C++ side). The shared reference fixture
// FlashIDA/test-data/config_schema_reference.json is GENERATED by the C# side
// (MethodParameters.GenerateReferenceConfigJson). This test proves:
//   - EveryKey_ParsesToOnDiskValue: the C++ Config reader binds every key to the value ON DISK
//     (parsed value == raw JSON value per field — no hard-coded sentinels, so it tracks the
//     generator automatically). If C++ silently defaults a key whose on-disk value differs, it fails.
//   - UnknownKey_Throws: the C++ Config reader hard-rejects any key with no schema home.
// The C# side (Flash.Tests/ConfigSchemaParityTests) proves the emitter + strict loader. Together the
// two schemas cannot silently diverge.
// ---------------------------------------------------------------------------

START_TEST(ConfigSchemaParity, "$Id$")

std::string json_str;
{
  std::ifstream in("../../FlashIDA/test-data/config_schema_reference.json");
  std::stringstream ss;
  ss << in.rdbuf();
  json_str = ss.str();
}

START_SECTION(reference_fixture_is_readable)
{
  TEST_EQUAL(json_str.empty(), false)
  TEST_EQUAL(json_str[0], '{')
}
END_SECTION

START_SECTION(EveryKey_ParsesToOnDiskValue)
{
  json j = json::parse(json_str);
  Config cfg(json_str);

  // --- deconvolution ---
  TEST_EQUAL(cfg.deconvolution().min_charge, j["deconvolution"]["min_charge"].get<int>())
  TEST_EQUAL(cfg.deconvolution().max_charge, j["deconvolution"]["max_charge"].get<int>())
  TEST_REAL_SIMILAR(cfg.deconvolution().min_mass, j["deconvolution"]["min_mass"].get<double>())
  TEST_REAL_SIMILAR(cfg.deconvolution().max_mass, j["deconvolution"]["max_mass"].get<double>())
  TEST_REAL_SIMILAR(cfg.targeting().qscore_threshold, j["deconvolution"]["score_threshold"].get<double>())
  TEST_REAL_SIMILAR(cfg.targeting().tqscore_threshold, j["deconvolution"]["tqscore_threshold"].get<double>())
  TEST_REAL_SIMILAR(cfg.targeting().tag_matching_tolerance_ppm, j["deconvolution"]["tol"][1].get<double>())

  // --- precursor_selection ---
  TEST_REAL_SIMILAR(cfg.targeting().rt_window, j["precursor_selection"]["rt_window"].get<double>())
  TEST_EQUAL(cfg.targeting().consider_all_charges, j["precursor_selection"]["consider_all_charges"].get<bool>())
  TEST_EQUAL(cfg.targeting().charge_based_exclusion, j["precursor_selection"]["charge_based_exclusion"].get<bool>())
  TEST_EQUAL(cfg.targeting().strict_inclusion, j["precursor_selection"]["strict_inclusion"].get<bool>())
  TEST_REAL_SIMILAR(cfg.targeting().tie_threshold, j["precursor_selection"]["tie_threshold"].get<double>())
  // targeting is a string enum on the wire and an int in the struct, so the parity check has to
  // map rather than compare directly. Mapping taken from the CODE (PrecursorSelection.cpp:138-141).
  {
    const std::string t = j["precursor_selection"]["targeting"].get<std::string>();
    const int expected = t == "inclusion" ? 1 : t == "in_depth" ? 2 : t == "exclusion_masses" ? 3 : 0;
    TEST_EQUAL(cfg.targeting().mode, expected)
  }
  // HCDEnergy is gone: its only export, PrecursorSelection::getIsolationWindows(), has zero
  // callers repo-wide, so the key could never affect an acquisition.

  // --- the MS1 selection keys, which moved here out of selection_strategy.ms1 ---
  TEST_EQUAL(cfg.level(1).max_targets, j["precursor_selection"]["max_precursors"].get<int>())
  TEST_EQUAL(cfg.level(1).min_charge, j["precursor_selection"]["min_precursor_charge"].get<int>())

  // --- flashtnt ---
  TEST_EQUAL(cfg.targeting().min_tag_length, j["flashtnt"]["min_length"].get<int>())
  TEST_EQUAL(cfg.targeting().max_tag_length, j["flashtnt"]["max_length"].get<int>())
  TEST_EQUAL(cfg.targeting().max_total_ptm_count, j["flashtnt"]["max_ptm_count"].get<int>())
  TEST_REAL_SIMILAR(cfg.targeting().max_flanking_mass_diff, j["flashtnt"]["max_flanking_mass_diff"].get<double>())
  TEST_EQUAL(cfg.targeting().allow_gap, j["flashtnt"]["allow_gap"].get<bool>())
  TEST_EQUAL(cfg.targeting().max_aa_in_gap, j["flashtnt"]["max_aa_in_gap"].get<int>())
  TEST_EQUAL(cfg.targeting().max_blind_mod_count, j["flashtnt"]["max_blind_mod_count"].get<int>())
  TEST_REAL_SIMILAR(cfg.targeting().max_mod_mass, j["flashtnt"]["max_mod_mass"].get<double>())
  TEST_EQUAL(cfg.targeting().fixed_mod.size(), j["flashtnt"]["fixed_mod"].size())
  TEST_EQUAL(cfg.targeting().fixed_mod.empty() ? std::string("") : cfg.targeting().fixed_mod[0],
             j["flashtnt"]["fixed_mod"][0].get<std::string>())

  // --- tagging.follow_up_scan ---
  // EVERY key, not a subset. This block previously asserted only the 4 keys Config happened to
  // parse, so the 9 it silently discarded were invisible here -- which is how a follow_up_scan
  // became unable to carry its own reaction_time. A follow_up_scan is a full scan config
  // (ADR-0009), so every key it declares must bind.
  //
  // follow_up_scan is a NAME now, so this follows the indirection into additional_ms2 rather than
  // reading an inline block. That makes the assertion strictly stronger: it proves the resolved
  // ScanConfig matches the JSON of the entry the name actually points at, so a resolver that picked
  // the wrong entry (or the first one by map order) would fail here.
  {
    const auto& fus = cfg.targeting().tagging_follow_up_scan;
    const std::string fname = j["tagging"]["follow_up_scan"].get<std::string>();
    const auto& jf = j["ms_settings"]["additional_ms2"][fname];
    TEST_EQUAL(fus.analyzer, jf["analyzer"].get<std::string>())
    TEST_EQUAL(fus.activation, jf["activation"].get<std::string>())
    TEST_EQUAL(fus.collision_energy, jf["collision_energy"].get<int>())
    TEST_EQUAL(fus.resolution, jf["resolution"].get<int>())
    TEST_EQUAL(fus.agc_target, jf["agc_target"].get<int>())
    TEST_REAL_SIMILAR(fus.max_it, jf["max_it"].get<double>())
    TEST_REAL_SIMILAR(fus.first_mass, jf["first_mass"].get<double>())
    TEST_REAL_SIMILAR(fus.last_mass, jf["last_mass"].get<double>())
    TEST_EQUAL(fus.microscans, jf["microscans"].get<int>())
    TEST_EQUAL(fus.data_type, jf["data_type"].get<std::string>())
    TEST_REAL_SIMILAR(fus.reaction_time, jf["reaction_time"].get<double>())
    TEST_REAL_SIMILAR(fus.reagent_max_it, jf["reagent_max_it"].get<double>())
    TEST_EQUAL(fus.reagent_agc_target, jf["reagent_agc_target"].get<int>())
  }

  // --- quantification.follow_up_scan (previously asserted NOWHERE) ---
  {
    const auto& fus = cfg.quantification().follow_up_scan;
    const std::string fname = j["quantification"]["follow_up_scan"].get<std::string>();
    const auto& jf = j["ms_settings"]["additional_ms2"][fname];
    TEST_EQUAL(fus.analyzer, jf["analyzer"].get<std::string>())
    TEST_EQUAL(fus.activation, jf["activation"].get<std::string>())
    TEST_EQUAL(fus.collision_energy, jf["collision_energy"].get<int>())
    TEST_EQUAL(fus.resolution, jf["resolution"].get<int>())
    TEST_EQUAL(fus.agc_target, jf["agc_target"].get<int>())
    TEST_REAL_SIMILAR(fus.max_it, jf["max_it"].get<double>())
    TEST_REAL_SIMILAR(fus.first_mass, jf["first_mass"].get<double>())
    TEST_REAL_SIMILAR(fus.last_mass, jf["last_mass"].get<double>())
    TEST_EQUAL(fus.microscans, jf["microscans"].get<int>())
    TEST_EQUAL(fus.data_type, jf["data_type"].get<std::string>())
    TEST_REAL_SIMILAR(fus.reaction_time, jf["reaction_time"].get<double>())
    TEST_REAL_SIMILAR(fus.reagent_max_it, jf["reagent_max_it"].get<double>())
    TEST_EQUAL(fus.reagent_agc_target, jf["reagent_agc_target"].get<int>())
  }

  // --- conditional_ms2 ---
  TEST_EQUAL(cfg.targeting().conditional_ms2_enabled, j["conditional_ms2"].get<bool>())

  // --- quantification ---
  TEST_EQUAL(cfg.quantification().enabled, j["quantification"]["enabled"].get<bool>())
  TEST_REAL_SIMILAR(cfg.quantification().reporter_mz_tol, j["quantification"]["reporter_mz_tol"].get<double>())
  TEST_REAL_SIMILAR(cfg.quantification().fold_change_threshold, j["quantification"]["fold_change_threshold"].get<double>())

  // --- faims ---
  TEST_EQUAL(cfg.faims().cv_values.size(), j["faims"]["cv_values"].size())
  TEST_REAL_SIMILAR(cfg.faims().cv_values[0], j["faims"]["cv_values"][0].get<double>())
  TEST_EQUAL(cfg.faims().max_cv_skip, j["faims"]["max_cv_skip"].get<int>())
  TEST_EQUAL(cfg.faims().precursor_threshold, j["faims"]["cv_precursor_threshold"].get<int>())

  // --- ms_settings.ms1 -> level(1).scans[0] ---
  const auto& ms1 = cfg.level(1).scans[0];
  const auto& jms1 = j["ms_settings"]["ms1"];
  TEST_EQUAL(ms1.analyzer, jms1["analyzer"].get<std::string>())
  TEST_REAL_SIMILAR(ms1.first_mass, jms1["first_mass"].get<double>())
  TEST_REAL_SIMILAR(ms1.last_mass, jms1["last_mass"].get<double>())
  TEST_EQUAL(ms1.resolution, jms1["resolution"].get<int>())
  TEST_EQUAL(ms1.agc_target, jms1["agc_target"].get<int>())
  TEST_REAL_SIMILAR(ms1.max_it, jms1["max_it"].get<double>())
  TEST_EQUAL(ms1.microscans, jms1["microscans"].get<int>())
  TEST_REAL_SIMILAR(ms1.rf_lens, jms1["rf_lens"].get<double>())
  TEST_REAL_SIMILAR(ms1.source_cid, jms1["source_cid"].get<double>())
  TEST_REAL_SIMILAR(ms1.source_cid_scaling, jms1["source_cid_scaling"].get<double>())
  TEST_EQUAL(ms1.data_type, jms1["data_type"].get<std::string>())
  TEST_EQUAL(ms1.scan_rate, jms1["scan_rate"].get<std::string>())

  // --- ms_settings.ms2 / ms3 ---
  // Both blocks assert ALL 17 keys. They used to assert 10 and 3 respectively -- the "assert only
  // the keys someone remembered" anti-pattern that the follow_up_scan blocks above were already
  // fixed for. A key nobody asserts is a key that can be dropped silently, which is how
  // rf_lens/source_cid/source_cid_scaling/scan_rate went missing from every MSn scan.
  const auto& ms2 = cfg.level(2).scans[0];
  const auto& jms2 = j["ms_settings"]["ms2"];
  TEST_EQUAL(ms2.analyzer, jms2["analyzer"].get<std::string>())
  TEST_EQUAL(ms2.activation, jms2["activation"].get<std::string>())
  TEST_EQUAL(ms2.collision_energy, jms2["collision_energy"].get<int>())
  TEST_EQUAL(ms2.resolution, jms2["resolution"].get<int>())
  TEST_EQUAL(ms2.agc_target, jms2["agc_target"].get<int>())
  TEST_REAL_SIMILAR(ms2.max_it, jms2["max_it"].get<double>())
  TEST_REAL_SIMILAR(ms2.first_mass, jms2["first_mass"].get<double>())
  TEST_REAL_SIMILAR(ms2.last_mass, jms2["last_mass"].get<double>())
  TEST_EQUAL(ms2.microscans, jms2["microscans"].get<int>())
  TEST_EQUAL(ms2.data_type, jms2["data_type"].get<std::string>())
  TEST_EQUAL(ms2.scan_rate, jms2["scan_rate"].get<std::string>())
  TEST_REAL_SIMILAR(ms2.rf_lens, jms2["rf_lens"].get<double>())
  TEST_REAL_SIMILAR(ms2.source_cid, jms2["source_cid"].get<double>())
  TEST_REAL_SIMILAR(ms2.source_cid_scaling, jms2["source_cid_scaling"].get<double>())
  TEST_REAL_SIMILAR(ms2.reaction_time, jms2["reaction_time"].get<double>())
  TEST_REAL_SIMILAR(ms2.reagent_max_it, jms2["reagent_max_it"].get<double>())
  TEST_EQUAL(ms2.reagent_agc_target, jms2["reagent_agc_target"].get<int>())

  const auto& ms3 = cfg.level(3).scans[0];
  const auto& jms3 = j["ms_settings"]["ms3"];
  TEST_EQUAL(ms3.analyzer, jms3["analyzer"].get<std::string>())
  TEST_EQUAL(ms3.activation, jms3["activation"].get<std::string>())
  TEST_EQUAL(ms3.collision_energy, jms3["collision_energy"].get<int>())
  TEST_EQUAL(ms3.resolution, jms3["resolution"].get<int>())
  TEST_EQUAL(ms3.agc_target, jms3["agc_target"].get<int>())
  TEST_REAL_SIMILAR(ms3.max_it, jms3["max_it"].get<double>())
  TEST_REAL_SIMILAR(ms3.first_mass, jms3["first_mass"].get<double>())
  TEST_REAL_SIMILAR(ms3.last_mass, jms3["last_mass"].get<double>())
  TEST_EQUAL(ms3.microscans, jms3["microscans"].get<int>())
  TEST_EQUAL(ms3.data_type, jms3["data_type"].get<std::string>())
  TEST_EQUAL(ms3.scan_rate, jms3["scan_rate"].get<std::string>())
  TEST_REAL_SIMILAR(ms3.rf_lens, jms3["rf_lens"].get<double>())
  TEST_REAL_SIMILAR(ms3.source_cid, jms3["source_cid"].get<double>())
  TEST_REAL_SIMILAR(ms3.source_cid_scaling, jms3["source_cid_scaling"].get<double>())
  TEST_REAL_SIMILAR(ms3.reaction_time, jms3["reaction_time"].get<double>())
  TEST_REAL_SIMILAR(ms3.reagent_max_it, jms3["reagent_max_it"].get<double>())
  TEST_EQUAL(ms3.reagent_agc_target, jms3["reagent_agc_target"].get<int>())

  // --- scheduling ---
  TEST_EQUAL(cfg.scheduling().cycle_time_enabled, j["scheduling"]["cycle_time"]["enabled"].get<bool>())
  TEST_REAL_SIMILAR(cfg.scheduling().cycle_time_ms, j["scheduling"]["cycle_time"]["value_ms"].get<double>())
  TEST_EQUAL(cfg.scheduling().timeout_enabled, j["scheduling"]["scan_timeout"]["enabled"].get<bool>())
  TEST_REAL_SIMILAR(cfg.scheduling().timeout_ms, j["scheduling"]["scan_timeout"]["value_ms"].get<double>())
  TEST_EQUAL((int)cfg.scheduling().agc_interval_ms,
             (int)(j["scheduling"]["agc_interval_seconds"].get<double>() * 1000.0))

  // --- characterization ---
  // `objective` is gone: its two values ARE the two on-values of `mode`, so it is derived rather
  // than authored. Asserting the derivation is what pins them together.
  {
    const std::string m = j["characterization"]["mode"].get<std::string>();
    TEST_EQUAL((int)cfg.characterization().objective,
               (int)(m == "coverage" ? CharacterizationObjective::Coverage
                                     : CharacterizationObjective::Ambiguity))
  }
  TEST_EQUAL(cfg.characterization().protein_sequence, j["characterization"]["protein_sequence"].get<std::string>())
  TEST_EQUAL(cfg.characterization().ms3_all_charges, j["characterization"]["ms3_all_charges"].get<bool>())

  // --- the projection: characterization.mode drives levels 2 and 3, and the MS3 budget/charge
  //     floor are AUTHORED in characterization but READ off level 2. Pinning both sides here is
  //     what stops the projection silently regressing.
  TEST_EQUAL(cfg.level(2).max_targets, j["characterization"]["max_targets"].get<int>())
  TEST_EQUAL(cfg.level(2).min_charge, j["characterization"]["min_fragment_charge"].get<int>())
  {
    const std::string mode = j["characterization"]["mode"].get<std::string>();
    const bool on = mode != "off";
    // Both gates move together -- MS3 requires level 2 AND level 3 non-None, so the incoherent
    // states are unrepresentable rather than merely discouraged.
    TEST_EQUAL(cfg.level(2).selection != SelectionMetric::None, on)
    TEST_EQUAL(cfg.level(3).selection != SelectionMetric::None, on)
    // Level 1 is projected from rank_by and is INDEPENDENT of mode. Asserted explicitly because
    // omitting it from the projection makes FLASHIda.cpp:168 short-circuit every MS1 and the
    // instrument acquires nothing at all.
    const std::string rank_by = j["precursor_selection"]["rank_by"].get<std::string>();
    TEST_EQUAL((int)cfg.level(1).selection,
               (int)(rank_by == "intensity" ? SelectionMetric::Intensity
                     : rank_by == "none"    ? SelectionMetric::None
                                            : SelectionMetric::QScore))
  }

  // --- exploration, now one block per decision section ---
  TEST_EQUAL((int)cfg.level(2).exploration, (int)ExplorationMetric::MassCount)
  const auto& jex2 = j["precursor_selection"]["exploration"];
  TEST_REAL_SIMILAR(cfg.level(2).ce_min, jex2["ce_min"].get<double>())
  TEST_REAL_SIMILAR(cfg.level(2).ce_max, jex2["ce_max"].get<double>())
  TEST_REAL_SIMILAR(cfg.level(2).ce_step, jex2["ce_step"].get<double>())
  TEST_REAL_SIMILAR(cfg.level(2).remaining_precursor_target, jex2["remaining_precursor_target"].get<double>())
  // tolerance_ppm is first-class now, not smuggled through the overrides map.
  TEST_REAL_SIMILAR(cfg.level(2).exploration_tolerance_ppm, jex2["tolerance_ppm"].get<double>())

  const auto& jex3 = j["characterization"]["exploration"];
  TEST_EQUAL((int)cfg.level(3).exploration, (int)ExplorationMetric::FragmentCount)
  TEST_REAL_SIMILAR(cfg.level(3).ce_min, jex3["ce_min"].get<double>())
  TEST_REAL_SIMILAR(cfg.level(3).ce_max, jex3["ce_max"].get<double>())
  TEST_REAL_SIMILAR(cfg.level(3).exploration_tolerance_ppm, jex3["tolerance_ppm"].get<double>())

  // --- the dispatch roster: ms_settings.ms2 first, then additional_scans IN ARRAY ORDER.
  //     Order must never come from iterating additional_ms2 -- nlohmann's object_t is a std::map,
  //     so that would alphabetise the names and silently reorder MS2 dispatch.
  TEST_EQUAL(cfg.level(2).scans.size(),
             1 + j["precursor_selection"]["additional_scans"].size())
}
END_SECTION

START_SECTION(GeneratedReference_CarriesEveryScanKey)
{
  // THE drift guard for this whole class of defect.
  //
  // The reference fixture is generated by the C# emitter; kScanKeys is defined by the C++ reader.
  // Asserting the former contains the latter makes the two impossible to drift apart silently,
  // in either direction:
  //   - C# drops a key   -> the regenerated reference lacks it            -> fails here
  //   - C++ adds a key   -> the reference has not caught up               -> fails here
  //   - C# adds a key    -> not in kScanKeys -> the Config ctor throws    -> fails above
  //
  // This is what was missing when commit 45c2cf9 trimmed rf_lens, source_cid, source_cid_scaling
  // and scan_rate from the C# MSn emit set as "always-default emit-only keys". Every one of them
  // was still in kScanKeys, still parsed by parseScanConfig, still copied by every ScanCommand
  // builder and still sent by ScanFactory -- they had simply become unreachable from method.json.
  // Nothing failed, because nothing compared the two lists (ADR-0011).
  json j = json::parse(json_str);

  // The five keys that live in IsolationStage rather than on the scan itself. kScanKeys is one
  // lenient union across all scan objects, but makeMS1 emits num_stages = 0, so these can never
  // reach an MS1 scan and the C# schema deliberately omits them there.
  const std::set<std::string> stage_carried = {
    "activation", "collision_energy", "reaction_time", "reagent_max_it", "reagent_agc_target"};

  // ms2 and ms3 are bare objects, and every extra MS2 -- including the two that back the follow-up
  // references -- lives in additional_ms2. The follow-up sites are DISCOVERED here rather than
  // named: j["tagging"]["follow_up_scan"] is a name string now, and hard-coding the generator's
  // chosen names would make this loop quietly stop covering a site the day one is renamed.
  std::vector<json> msn_sites = {j["ms_settings"]["ms2"], j["ms_settings"]["ms3"]};
  if (j["ms_settings"].contains("additional_ms2") && j["ms_settings"]["additional_ms2"].is_object())
    for (const auto& entry : j["ms_settings"]["additional_ms2"])
      msn_sites.push_back(entry);
  TEST_EQUAL(msn_sites.size() >= 3, true)  // else the reference stopped covering the follow-ups

  for (const auto& key : Config::scanKeys())
  {
    for (const auto& site : msn_sites)
    {
      // Reported as a key/bool pair so a failure names the missing key rather than just "0 != 1".
      TEST_STRING_EQUAL(key + "=" + (site.contains(key) ? "present" : "MISSING"), key + "=present")
    }
    if (stage_carried.count(key) == 0)
    {
      const auto& ms1 = j["ms_settings"]["ms1"];
      TEST_STRING_EQUAL("ms1." + key + "=" + (ms1.contains(key) ? "present" : "MISSING"),
                 "ms1." + key + "=present")
    }
  }

  // And the converse for ms1: a stage-carried key appearing there would mean the C# schema had
  // started emitting something an MS1 command structurally cannot carry.
  for (const auto& key : stage_carried)
  {
    const auto& ms1 = j["ms_settings"]["ms1"];
    TEST_STRING_EQUAL("ms1." + key + "=" + (ms1.contains(key) ? "UNEXPECTED" : "absent"),
                      "ms1." + key + "=absent")
  }
}
END_SECTION

START_SECTION(UnknownKey_Throws)
{
  // A key with no schema home must throw std::invalid_argument at parse time — at every level.
  TEST_EXCEPTION(std::invalid_argument, Config(std::string(R"({ "bogus_top": 1 })")))
  TEST_EXCEPTION(std::invalid_argument, Config(std::string(R"({ "precursor_selection": { "bogus": 1 } })")))
  TEST_EXCEPTION(std::invalid_argument, Config(std::string(R"({ "ms_settings": { "ms1": { "IsolationMode": "Quadrupole" } } })")))
  TEST_EXCEPTION(std::invalid_argument, Config(std::string(R"({ "flashtnt": { "typo": 1 } })")))
  TEST_EXCEPTION(std::invalid_argument, Config(std::string(R"({ "ms3": { "enabled": true } })")))   // legacy top-level section
}
END_SECTION

END_TEST
